apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: k8s-app
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx
      containerPort: 80
  - name: watcher
    image: afakharany/watcher
    ports:
    - name: watcher
      containerPort: 80
    
